const Routes = {
  FOLDERSTRUCTURE: 'folder_structure',
  DRAG_AND_DROP: 'drag_and_drop',
  SELECTABLE_GRID: 'selectable_grid',
  GRID_LIGHTS: 'grid_lights',
  LIKE_BUTTON: 'like_button',
  BREADCRUMBS: 'bread_crumbs',
  EMI_CALCULATOR: 'emi_calculator',
  AUDI_SIGN: 'audi_sign',
  SCRATCH_CARD: 'scratch_card',
  SCROLL_PERCENTAGE: 'scroll_percentage',
  INFINITE_SCROLL: 'infinite_scroll',
  TYPE_AHEAD: 'type_ahead',
  PAGINATION: 'pagination',
  TABLE: 'table',
  STEPPER: 'stepper',
  INTERSECTING_CIRCLE: 'intersecting_circle',
  START_TO_END_NUMBER_SPINNER: 'start_to_end_spinner',
  GOOGLE_DOC_BULLET: 'google_doc_bullet',
  PASSWORD_GENERATOR: 'password_generator',
  PROGRESS_BAR: 'progress_bar',
  JOB_BOARD: 'job_board',
  DARK_MODE: 'dark_mode',
  OTP_LOGIN: 'otp_login',
  QUIZ_APP: 'quiz_app',
  CURRENCY_CONVERTER: 'currency_converter',
  TIC_TAC_TOE: 'tic_tac_toe',
};
export default Routes;
